### ISSUE TITLE
Using Apple two step verification

### ISSUE THREAD

**Issue by frekel** [vmtyler/ical-sensor-homeassistant#5]
Is this possible?  And if so, can you point me in the right direction?

**Comment by vmtyler** [comment]
I don't think so- you might be able to create an app-specific password. You'd also need to add the auth code to this as well (OAUTH i think) which isn't trivial and generally requires your app to have a publicly accessible webhook url.

I guess the best way to put it is if you have to ask, it's probably beyond your capabilities.

**Comment by frekel** [comment]
I already tried the app-specific password but that gives an login error. Thanks for the info! 
I will revert to normal authentication.
